---
title: "Alternative Models"
author: "Anamay Shetty"
date: "16/12/2020"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rethinking)
theme_set(theme_minimal())
knitr::opts_chunk$set(echo = FALSE, include = FALSE)
```

This files dicusses alternative models for our dataset


1. Straight-line model

2. Varying parameters

3. Adaptive priors

4. Latent variable model

```{r}
train <- read_tsv("data/train.txt")

train <- train %>%
  mutate_at(c("BMAT_Section_1", "BMAT_Section_2"), ~(. - mean(.)) / sd(.))

```

```{r}
latent_model <- ulam(
  alist(
    Offer ~ dbinom(1, p),
    logit(p) <- a + b * Smarts[Candidate_ID],
    a ~ dnorm(-1, 1.5),
    b ~ dlnorm(1, 0.25),
    BMAT_Section_1 <- beta1[Candidate_ID] + Smarts[Candidate_ID],
    BMAT_Section_2 <- beta2[Candidate_ID] + Smarts[Candidate_ID],
    beta1[Candidate_ID] ~ dnorm(0, 0.5),
    beta2[Candidate_ID] ~ dnorm(0, 0.5),
    Smarts[Candidate_ID] ~ dnorm(0, 1)
  ),
  data = train, chains = 4, log_lik=TRUE
)
```

